### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by florangelica** [SirUsername/flow#9]
Initial page that users will arrive to needs to be done before we can really do much.

**Comment by GTFMyrmidon** [comment]
Fix preloader by disabling scrolling during loading, or remove entirely

**Comment by joelhmarquez** [comment]
The logo consists of 2 arrows going an opposite way.

**Comment by joelhmarquez** [comment]
The loading is long but it still needs a smaller loading time??

**Comment by joelhmarquez** [comment]
The page was optimized for mobile.
